### ISSUE TITLE
Commit 9e1d562

### ISSUE THREAD

**Issue by deligkaris** [jburke5/microsim#40]
CD

One significant drop I noticed for the RRs in the notebook JB gave me is the one going from commit 1dc4598 to commit 9e1d562. Commit 1dc4598 is the last one I am finding a mean RR 0.75 and commit 9e1d562 is the first one that this number drops to about 0.70 and stays there for all subsequent commits. 

Running older commits sometimes results in errors...I assume the code may be significantly different and I do not know the exact time in point this notebook was written....

I will see if commit 9e1d562 (Fixing logic of treamtent effects to separate out antiHypertensives from bpMedsAdded and calibrating on that) can possibly result in the discrepancy I notice on the RRs...

*****
JB

The thing that I was addressing for the first paper was that we only want to recalibrate the effect of medications added for BP control so that we can compare to usual care instead of the number of BP medications that a patient is on. (i.e. we want to take usual care as a given — our CV risk models are normed on usual care…the effect of treatment is, then, derived from trials — and we want to identify the effects of each treatment that you add, not of each treatment that you are already on…)

*****

CD

Note 1: The notebook that we use for validation is using AddASingleBPMedTreatmentStrategy, therefore whatever affected the RRs is either part of that class or code that this class is using (no need to focus on the rest of the code in bp_treatment_strategies.py).

Note 2: In bp_treatment_strategies.py line 26, I think antihypertensivecount should not be set to 1, but rather keep that dictionary empty because the single medication is added on the bpmedsadded variable. This method is used in person.py line 666 as part of the person advance_treatment method and those changes are applied to each person in this method. However, I do not see a reference of this method on the population.py file so population classes do not seem to use it (could be a different bug or not, not sure).

On the same person.py advance_treatment method, antihypertensivecount is used and I wonder if totalbpmeds should be used instead. Even if that is the case, I do not think this affects the RRs because it is not used in population classes.

Note 3: In this addsinglebpmed class, in method get_changes_vectorized, when I add the code line that was deleted in this commit, x.antiHypertensiveCountNext = x.antiHypertensiveCountNext + 1, that brings the RRs to what we were getting prior to this commit. When this line is present, even when I do x.bpMedsAddedNext = 0, the RRs remain the same as they were prior to this commit. Which suggests that the effect of antihypertensivecount and bpmedsaddednext is not symmetrical, but I am not sure if their effects should be symmetrical. Q: should it make a difference if a medication is part of antihypertensives or bpmedsadded? JB's comment above is not clear to me, but it may mean that the two variables should have asymmetrical effects.

Note 4: cohort_risk_model_repository.py : unsure what the repository is doing, but it is only using antihypertensivecount and I wonder if totalbpmeds should be used instead.

Note 5: In the last few person.py methods (equal, ne, deepcopy etc), the bpmedsadded attribute are not included and I wonder if they should be included. It is not clear to me how, and if, this may affect the RRs as it depends on whether population classes use these person methods.

Note 6: static_risk_factor_over_time_repository: is using the repository but not sure why, and it is only using antihypertensivecount, I am not sure if totalbpmeds should be used instead.

**Comment by deligkaris** [comment]
Notes 4 and 6: 

I have a few related variables on this...

antiHypertensive refers to medications as a response to actual high blood pressure
bpMedsAdded refers to medications added but not as a response to an actual problem
totalBpMedsAdded is the sum of bpMedsAdded (and it does NOT include antiHypertensives)

A person instance has the definition of
"current_bp_treatment": self._antiHypertensiveCount[-1] > 0

So, the sum of all BP medications would be antiHypertensiveCount + totalBPMedsAdded (not just totalBpMedsAdded as I though in my previous note).

Interestingly, the gcp_model has:
anyAntiHpertensive=((person.antiHypertensiveCount + person.totalBPMedsAdded)> 0),

But as noted in Note 4 and 6, those repository/risk models are using only antiHypertensive.

It is not clear to me if the repository and all risk models should be doing the same thing the gcp_model is doing....

**Comment by deligkaris** [comment]
I run two microsim simulations on the notebook one using the current master branch and one where I add 1 antihypertensive. 

Comparing the outputs, I noticed that the [delta values](https://github.com/jburke5/microsim/blob/93df63fd58413cd43d8f1a6502e7ca50bd0d2c1f/microsim/population.py#L467)) are identical both over the years and in the two simulations. This could be either the problem or I have not run the simulation long enough to allow the risks to change and introduce variations of size large enough to show up in the deltas, or the deltas are fine by being constant....

If this is the problem, then I think that treatment_outcome_standard[outcomeType] should be a constant and depend on whether we are talking about MIs or strokes. So, then the first term seems to be a constant and it should not...which means that [estimate_risks](https://github.com/jburke5/microsim/blob/93df63fd58413cd43d8f1a6502e7ca50bd0d2c1f/microsim/population.py#L423) is producing always identical risks...

**Comment by deligkaris** [comment]
I am finding that modelEstimatedRR is always 1 even in commit 1dc4598 which is supposed to be the last one where the RRs turn out to be correct...

The deltas are always 0.21 (1-0.79) for stroke and 0.13 (1-0.87) for mi. 0.79 and 0.87 are the two constants associated with stroke and mi.

Currently, what I am suspecting is that commit 9e1d562 altered the risks and probabilities but kept the percentage of events to rollback constant. So, the change in the relative risks with this commit seems to have originated from a change in the number of events due to a change in risks and probabilities without a simultaneous change in the percentage of events to rollback.

**Comment by deligkaris** [comment]
I think the number of events changed because the [outcome_model_repository](https://github.com/deligkaris/microsim/blob/master/microsim/outcome_model_repository.py) on line 94 shows how to get the CV outcome determination and this depends on the coefficients shown a bit above, eg on line 54 for female. One of these coefficients is current_bp_treatment and that depends only on the antihypertensives because a person instance has the definition of "current_bp_treatment": self._antiHypertensiveCount[-1] > 0. So perhaps this explains why the number of events changed with this commit.

**Comment by deligkaris** [comment]
As far as why the modelEstimatedRR stay the same: this is using the estimate_risk function in population.py which relies on get_stroke_probability which relies on [estimate_next_risk_vectorized ](https://github.com/deligkaris/microsim/blob/master/microsim/statsmodel_linear_risk_factor_model.py) and it is not clear to me if this produces the same probabilities as the ones used to determine events...based on the results from the simulation I am guessing that they are not the same....

**Comment by deligkaris** [comment]
In bp_treatment_strategies.py, AddSingleBPMedTreatmentStrategy, the get_changes_vectorized (and rollback too) assume that bpMedsAdded is zero (1 for rollback). If AddSingleBPMedTreatmentStrategy is applied after a different BP treatment strategy this assumption will not be true and the bp meds count and blood pressure will not be consistent with each other.

**Comment by deligkaris** [comment]
I just noticed this comment in person.py that seems to be relevant:

 # this variable is used in the risk model...
 # this reflects whether patients have had medications assigned as a risk factor, but 
 # not whether there has been a separate trematent effect, which is tracked in bpMedsAdded
 "current_bp_treatment": self._antiHypertensiveCount[-1] > 0,

So, changing the definition of current_bp_treatment in population.py and person.py (there are a few places in person.py that the code needs to be changed too) alters the probabilities used to determine events and makes them the same as the probabilities prior to commit 9e1d562. 

It is still not clear to me that this is desirable or if we should change the modelEstimatedRR that is currently a constant and independent of the population dataframe.

**Comment by deligkaris** [comment]
JB:

k, great…so, we’ve isolated the problem. that seems like a step in teh right direction…there is progress, but we’ve still got some things to figure out...

if “current_bp_meds” includes bpMedsAdded AND antiHypetensiveCount, we get the same answer.

i think there are 2 main questions, then…and they’re related.
1. WHY does this fix the problem?

here is were i’m still confused. the degree of relative recalibration (the number of events that we change) is based on 3 factors — delta, the number of events and the modelEstimateRR (line 470)


numberOfEventStatusesToChange = abs(

int(round(delta * len(eventsForPeople) / modelEstimatedRR))

)

but, if delta and modelEstimateRR are the same for both interpretations of current_bp_meds, then how are we changing a different relative number of events? i don’t get it…

i can see how the length of eventsForPeople would change depending on how we define current_bp_meds (i.e. more people on meds -> higher risk -> more events), but the relative effects (what we’re recalibrating on), shoudl come to out the same, right?

2. what SHOULD current_bp_meds be set at?

i think that the comment is quite helpful here! it reminds me of my prior thinking…

antiHypertensiveCount is defined on the basis of population level data — it’s mostly a risk factor. if you are on medications, you are higher risk than if you are not. so…we should NOT include it current_bp_meds, because that variable is used in our risk models. 

so, i think that the current version of current_bp_meds is the “right” answer

i think, then, that we have to solve the hard problem #1 above — WHY dods changing current_bp_meds fix the problem…and, once we understand that…how can we get the “right” answer!

**Comment by deligkaris** [comment]
A thought about a potential issue that may be relevant...

The advance_treatment person method includes:

if not self._bpTreatmentStrategy.repeat_treatment_strategy():
                self._bpTreatmentStrategy = None

But there is nothing in population.py that stops the treatment from being applied after it is applied it that treatment is not supposed to be repeated (according to the repeat_treatment_strategy).

Something related to this is also that in bp_treatment_strategies.py addSingleBPMedTreatement it should be:

x.totalBPMedsAddedNext = x.totalBPMedsAddedNext + 1

and then rolling back should be

x.totalBPMedsAddedNext = x.totalBPMedsAddedNext - 1

This is also relevant to this [comment.](https://github.com/jburke5/microsim/issues/40#issuecomment-1460305304).

**Comment by deligkaris** [comment]
But when I try to terminate a non-repeatable treatment at the end of the first year, then there is no recalibration done, even though the totalBPMedsAdded was 1.

There is no recalibration after the 1st year because of this in population.py:

def apply_recalibration_standards(self, recalibration_df):
        # treatment_standard is a dictionary of outcome types and effect sizees
        if self._bpTreatmentStrategy is not None:
            if self._bpTreatmentStrategy.get_treatment_recalibration_for_population() is not None:
                recalibration_df = self.recalibrate_bp_treatment(recalibration_df)
        return recalibration_df

**Comment by deligkaris** [comment]
JB

so, it think this probably isn't a problem…this was a workaround for the fact that antiHypertensiveCount and bpMedsAdded were combined. but, it think its not relevant any time soon...

if you wanted to do a “addOneMedication” type treatment algorithm, then you only wanted to add it once, not every year and this wa sa way of turning it off.

for our actual BP treatment algorithms (i.e. SPRINT), it looks at how many total meds you are on and then adds from there…so, i don’t thikn it sa huge problem.

for the “AddASingleBPMedTreatmentStrategy” algorithm, i thikn it works ok because it sets it at “1” and doesn’t add one…

**Comment by deligkaris** [comment]
JB

oh, good point! there shoudl not be recalibration if there is no treatment. 

although, given that there is no target for recalibration i assume its not actually happening or that its not doing anythign when it happens...

**Comment by deligkaris** [comment]
As is now, there is treatment every year, even though it should only be on year 0, and it does do a recalibration every year because x.totalBPMedsAddedNext = 1 is set every year in addSingleBPTreatment and the [recalibration dataframe depends on totalBPMedsAddedNext](https://github.com/deligkaris/microsim/blob/master/microsim/population.py#L340)...

**Comment by deligkaris** [comment]
JB

so, it SHOUDL do the recalibration every year.

BP medications have an effect every year, not just the first year that you start them…

so, i think that’s right...

**Comment by deligkaris** [comment]
OK....I have a feeling that by a cancellation of errors it is now doing the correct thing as far as this is concerned so I can table this for now and come back to fix it after I figure out the important stuff...

Which for now, I am focusing on modelEstimateRR and why it turns out to be 1 all the time...

**Comment by deligkaris** [comment]
An update: the [estimate_risks](https://github.com/deligkaris/microsim/blob/master/microsim/population.py#L423) function produces identical risks, mi and stroke, for the treated and untreated groups and I have yet to find a variable that affects those risks (I will keep looking).

I can see that treatment affects the sbp and totalBPMedsAdded numbers on the recalibration dataframes but those changes do not affect at all the risks produced by estimate_risks.

A question is, should it affect the risks in the first place?  It seems to me that sbp is a coefficient in the outcome_model_repository so if you lower sbp the risk should change....but it did not...I thought maybe the sbp coefficient is too small to see an effect so I increased it by a factor of 1000 and I still did not see a difference in the risks of treated and untreated....

So, the treated and untreated dataframes are different, as they should, but for some reason estimate_risks produces identical risks...so this is the next thing to look into....

I also modified antiHypertensives which modifies current_bp_treatment attribute which would then alter the risk, my guess, but even this did not change the treated and untreated risks...

**Comment by deligkaris** [comment]
JB

ok…i have a good guess as to what the problem is…

when hte risks are calculated on teh reclibration_df, it hasn’t yet been updated. so, the risk factors, treatment and outcomes have been updated…but they’re updated on the *Next variables. when you run the CV risks on it, it looks at the current values of SBP, antiHypertensiveCount, etc. they aren’t changed…because those updates are in teh *Next variables.

if that’s right, then my theory would be that if we move this line (population, 202)


alive = self.move_people_df_forward(alive)



ahead of this line (population, 182)


alive = self.apply_recalibration_standards(alive)


that we’ll get it back in gear. i think that the recalibration isn’t seeing what happened in this wave at all…

conceptually, the problem is that recalibration shoudl be the LAST thign that we do — first, update everything THEN, recalibrate it…

**Comment by deligkaris** [comment]
From a quick test, it seems that your guess is correct, changing the latest risk factors using their *Next values does make the treated and untreated risks different. 

I cannot simply copy and paste the move_people_df_forward to above where the recalibration is done because what is done in between those 2 lines is used by move_people_df_forward....

One thought would be to provide to estimate_risks functions dataframe copies for treated and untreated where their latest values  are obtained from the recalibrate_df *Next values.....

Or perhaps to create an estimate_next_risks function....

I will also need to understand what attributes the estimate_risks function is using so that I can make sure the correct values are used....

**Comment by deligkaris** [comment]
To calculate the risks, is the code using only the male and female coefficients included at the beginning of [outcome_model_repository?](https://github.com/deligkaris/microsim/blob/master/microsim/outcome_model_repository.py) 

Does lagAge corresponde to _age[-1]? Does the translation from "lag" to [-1] take place [here?](https://github.com/deligkaris/microsim/blob/master/microsim/statsmodel_linear_risk_factor_model.py#L55)

Finally, does the partition of risks to stroke and mi risks, in get_stroke_probability using exactly the same coefficients as the ones I mention above?

If I understand correctly those attributes (male and female coefficients) are the ones I need to pass correctly to estimate_risks, but I want to double check....

**Comment by deligkaris** [comment]
JB

o calculate the risks, is the code using only the male and female coefficients included at the beginning of [outcome_model_repository?]

yep.

Does lagAge corresponde to _age[-1]? Does the translation from "lag" to [-1] take place [here?](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Furldefense.com.mcas.ms%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fdeligkaris%2Fmicrosim%2Fblob%2Fmaster%2Fmicrosim%2Fstatsmodel_linear_risk_factor_model.py*L55__%3BIw!!AU3bcTlGKuA!By-3aTxxOPWZ_ZYs4WBTUKSdvT_pGYvrKghWnGyReqyBIbv8htl3NfJXisdnJOJNnEO83FJNfW_idCrV3CXJCe0fDZSJ%24%3FMcasTsid%3D20893&McasCSRF=e458616be65c292a5a721060beaaa9789f25e67f997724b802723e038a6ff730)

yep and yep

Finally, does the partition of risks to stroke and mi risks, in get_stroke_probability using exactly the same coefficients as the ones I mention above?

not quite. its modeled as a RiskModel using these coefficients: https://github.com/jburke5/microsim/blob/master/microsim/data/StrokeMIPartitionModelSpec.json

If I understand correctly those attributes (male and female coefficients) are the ones I need to pass correctly to estimate_risks, but I want to double check....

—


so, my thought would be to do something like this:
1. move up most of the  move_people_df_forward() method so that the risk factors and outcomes are all advanced prior to recalibration
2. pull otu the parts of move_people_df_forward() method that need to happen after the parts between move_people_df_forward() and apply_recalibration_standards()

into a separate method...

**Comment by deligkaris** [comment]
It seems to me that things are tangled....what I mean: 

If we need to use the *Next values in estimate_risk in order to do the recalibration, this includes the next age (as an example), to get the next age we need to know if this person has had a fatal outcome or not, to know the outcomes we need to do the recalibration of the treatment and outcomes...

Also if we move the people dataframe forward in order to do the recalibration using *Next values, then this:

alive["nonCVDeathNext"] = alive.apply(
                self._outcome_model_repository.assign_non_cv_mortality_vectorized, axis="columns"
            )

will also take place using *Next values which is different than what the simulation has been doing up to now...

And also, the create or rollback events for recalibration are operating on *Next variables, if all those are moved to the latest, ie [-1] values, then all new/rollbacked events will need to operate to the latest values but it will be somewhat difficult to keep track of what took place in this year and what took place in the past...

A thought I had about copying the alive dataframe, moving the *Next values to the latest ones and providing this modified dataframe to estimate_risks may not work. It seems to me to get the risks using *Next values, I need to have even all person instances updated (because the risk calculation is using the [-1] attribute of age (eg) and this is obtained from person instances in [this method](https://github.com/deligkaris/microsim/blob/master/microsim/statsmodel_linear_risk_factor_model.py#L55)).

I will keep looking into this...

**Comment by deligkaris** [comment]
JB

so, i think that the “next” values are correct. the trick is how to deal with death.

the thing that is strange is that population.advance() is describing a process. at the start of the process…we update the risk factors, in the middle we update the treatment and outcomes, etc. recalibration is at the END of the process. but it is recalibrating the “current” step in teh process, which is to say that it shoudl operate on teh “next” values. 

i think what we want to do is:
1. set all “next” risk factors, treatments and outcomes.
2. update the data frame so that the “next” element are now the “current” elements (i.e. call:
self.move_people_df_forward(alive)
3. assign QALYs (they’ll be based on teh updated events).
4. advance age
5. push the updates to teh person objects.

**Comment by deligkaris** [comment]
JB

my thought was that it’d be easier (and possibly cleaner) to update the alive data frame so that the “Next” variables are moved into the position of the “regular” variables and THEN recalibrate.

why wouldn’t that work?

it will require some tweaks (i.e. the lines below will need to operate on the “regular” variables instead of the “Next” variables), but it seems like shoudl work to me. am i missing something?


recalibration_df.loc[

recalibratedForMedCount.index, "strokeNext"

] = recalibratedForMedCount["strokeNext"]

recalibration_df.loc[

recalibratedForMedCount.index, "strokeFatal"

] = recalibratedForMedCount["strokeFatal"]

recalibration_df.loc[

recalibratedForMedCount.index, "deadNext"

] = recalibratedForMedCount["deadNext"]

recalibration_df.loc[

recalibratedForMedCount.index, "ageAtFirstStroke"

] = recalibratedForMedCount["ageAtFirstStroke"]

recalibration_df.loc[

recalibratedForMedCount.index, "rolledBackEventType"

] = recalibratedForMedCount["rolledBackEventType"]

**Comment by deligkaris** [comment]
One thing that I am not sure about now...

I just realized that the "vectorized" methods are applied on person instances, I think at least...and those are updated only at the end....

But, when I modified the alive dataframe's "sbp" values for the untreated group (I did that manually) it did affect the modelEstimatedRR, so it seems to me that changing the dataframe did affect the risk calculations even though based on what I understand now it should not...

Am I wrong that the "vectorized" methods are applied on the person instances and do not use the population dataframe at all?

**Comment by deligkaris** [comment]
I changed my mind, "vectorized" refers to a single line on the alive dataframe because a single person instance is represented as a single line on the dataframe...so "vectorized" refers to applying functions in parallel (the pandas parallel) to the alive dataframe lines...

**Comment by jburke5** [comment]
yep!
