### ISSUE TITLE
convert random number generator into a singleton

### ISSUE THREAD

**Issue by jburke5** [jburke5/microsim#52]
as it stands, the random number generator is initiated early in teh process and then passed around. rather than doing that, a cleaner way to do this may be to have a single randomNumberGenerator class per microsim instance with accessor methods (i.e. get_random_number_generator()). this may simplify the number of times we have to pass that parameter...

**Comment by deligkaris** [comment]
Each person object now has their own random number generator. There is no need to pass around rngs...
