### ISSUE TITLE
PersonRowWrapper class in outcome_model_repository

### ISSUE THREAD

**Issue by deligkaris** [jburke5/microsim#65]
As far as I understand PersonRowWrapper is used to create a dummy person object, I assume because some functions in outcome_model_repository utilize person attributes (so probably there is no vectorized version of them). I wonder if it is possible to use the index stored on the alive df to find the exact person instance and use that in outcome_model_repository instead of PersonRowWrapper. Using an actual person instance would also allow us to use person methods (eg in deciding which GCP model to use for a person-row on the alive df I could use the has stroke person method). 

If the goal of this dummy person class is to avoid completely the use of person methods then perhaps we could enhance the outcome_model_repository methods with vectorized approaches.

Is my understanding correct? What do you think?

**Comment by jburke5** [comment]
your understanding is correct. it is just a workaround to enable the codebase to work with vectorized data or person objects without too much redundancy.

i think the main reason that i didn’t use actual person objects was based on memory and data overhead — the idea was that by using a simple wrapper object that it wouldn’t add much of a performance/memory hit. 

maybe do a trial on a performance comparison? code-wise, i agree it’d be cleaner to kill the personWrapper class and just uses persons...

**Comment by deligkaris** [comment]
A summary of our discussion today:

1) The PersonRowWrapper class has as a goal to avoid the creation of person objects and hence to not increase memory usage.
2) If Microsim is run on a distributed environment then with this class, there will not be need to transfer data between cores.
3) Every time the outcome_model_repository needs information that is not stored on the dataframe, we will need to add an attribute to the PersonRowWrapper class. If we end up having a lot of attributes on this class, then it will be difficult to keep track of things, we will have the same information stored more than once (actually 3 times, one on person objects, one on the df, and one on the PersonRowWrapper).
4) If the df includes the person object index so that we can fetch the person object (the one that already exists, not creating a new instance) we could here fetch that person object and use person methods to decide which model to use. This does not create any increase in memory usage (probably).
5) The priority for now is to finish the implementation of the stroke phenotype model. Once that is done, we should come back to this issue and do the following test: use the person objects and advance the risk factors (without using the df at all) and then do the same thing using the advance vectorized method on the dataframe in order to compare which approach is faster and uses less memory.

**Comment by deligkaris** [comment]
The person-based code is not using PersonRowWrapper at all.
