### ISSUE TITLE
performance tests (regarding the use of dataframes and objects)

### ISSUE THREAD

**Issue by deligkaris** [jburke5/microsim#71]
Currently the simulation can operate either with the use of person objects or person rows as part of a dataframe.

There is a need to perform tests and determine the relative efficiency of these two approaches.

Questions that would be useful to answer and some related thoughts:

1) Can the person-object version be written such that the simulation processes these objects in parallel using more than 1 core? 

The answer is yes since this was done some time ago by @jburke5 and the code can be found in the history of the code.

2) What is the relative performance of the person-object version and the dataframe version when those run on a single core? In terms of both speed and memory requirements.

3) Regarding the implementation in 1 above, to what extent is the recalibration a bottleneck? After each wave, the cores will need to report back so that the recalibration can take place. The number of people assigned to a core may be an important parameter here, since if there are too few person objects assigned to a core the relative communication overhead will be high. 

4) Will recalibration be always taking place? 

5) One approach would be to create populations large enough so that recalibration can meaningfully take place and send each population to a core in order to eliminate much of the communication overhead. This could be done with either the dataframe version or the person object version.

6) A column in a dataframe can be a list. What is the relative cost of accesing a list in a single column or multiple columns of the dataframe in order to get the same information?

7) Instance attributes and dataframe columns can be accessed in an identical way: instance.attribute, dataframe.column. Does this allow the code to be rewritten so that exactly the same code works in either the object version or the dataframe version?

8) Is there a plan for pandas to natively support the use of multiple cores in the future?

9) Currently, the dataframe stores mean values at the cost of memory but perhaps allowing increased efficiency due to avoiding repeated calculations of the same quantity. The same is not being done currently with person objects which costs time but reduces memory requirements.

**Comment by deligkaris** [comment]
I found one point in time when multiprocessing was used....some important observations about that implementation:

1) Iterating over the population using a [for loop](https://github.com/jburke5/microsim/blob/1f3db94da9d0ffd698d63a3785eed33fa7a36af1/mcm/population.py#L58) is probably the least efficient way to apply a function....using map would be faster....

2) For every year the population advances, the population is [serialized/deserialized and transferred back and forth ](https://github.com/jburke5/microsim/blob/1f3db94da9d0ffd698d63a3785eed33fa7a36af1/mcm/population.py#L74) from the main core to the multiprocessing cores.  This increases the computing cost as there is an overhead cost to using multiprocessing (unless of course the entire population must be moved back and forth but then the cost of the overhead needs to be compared with the cost of the computation cost while on the MP core).  For example, recalibration standards are applied on the population when that is returned after a year of advancement, so then the questions are: a) does the entire population need to be returned to perform recalibration? b) can recalibration be parallelized in a way because that would be the bottleneck for an efficient implementation of multiprocessing.

**Comment by jburke5** [comment]
1. definitely true. i’m also pretty sure that was a workaround because map was failing for some reason.
2. this, i thikn, is the key question. if you tests show that multiprocessing is much faster than the data frame based population, then i think we have to figure this out.

i think the simplest general approach is:
— build a separate module to define recalibration coefficients (i.e. “first, find a recalibration coefficient”)) 
— then apply those recalibration coefficients appropriately in the risk models accounting for treatment (we can do this now because bp meds added are tracked separately from “usual care” anti hypertensive medications)

jim

**Comment by deligkaris** [comment]
I will summarize some of the findings that resulted from the [work on comparing dataframe and object representations.](https://github.com/deligkaris/microsimNotebooks/blob/main/DataframeVsObjects.ipynb) 

When a single core is used:

1) Appending results is faster using the person objects.
2) Calculating a risk factor and appending it is faster using the person objects.
3) Accessing and using multiple person attributes is much faster than using multiple dataframe columns.
4) Accessing and using a single person attribute list is about equally fast as using a single column-list.
5) Accessing and using multiple attribute-lists is much faster than using multiple dataframe column-lists.
6) When the population advances a few years, the increased amount of data does not affect the computing cost significantly.

When multiprocessing is used:
1) Serializing and deserializing person objects is much much slower than ser/deser dataframe when the dataframe is broken in a small number of pieces. It is not the data structure of a person object that causes this large cost, it is due to a large number of objects that need to be ser/deser that causes this. Similarly, if the dataframe is broken in a large number of pieces, eg each row is a separate pd.Series, then ser/deser that population takes a very long time.
2) Accessing and using a single column-list is much faster than using a single attribute-list.
3) Calculating and appending several risk factors with the dataframe is faster than using person objects.
4) There is a cost (ser/deser) associated with both sending the population to the cores and sending it back to the main core. So, if the population need to be transferred one way only, that would save in that type of cost.

I will now follow up with some thoughts on these results....

**Comment by deligkaris** [comment]
Some thoughts.....

1) In terms of single core speeds, using the person objects is a faster approach (assuming for loops over the population can be entirely avoided).
2) It is unreasonable to assume that for the future, the simulation will be run entirely on a single core, so the scalability issue need to be taken into account.
3) I have not found a way to "bundle" a portion of the person-objects that comprise the population to a single data structure that allows it to have a reduced multiprocessing overhead cost (ser/deser). Even if there is such a way, we will need to take into account the cost of creating that structure in the first place so it is unclear if that would yield any benefit anyway.  
4) If the simulation overall computing time is much longer compared to the multiprocessing overhead cost then using a person-object approach might yield an improvement over the pandas approach, eg if the population is transferred only once during the simulation. Regarding this, I also imagine distributing the population creation to the cores for parallel processing but then the nhanes data would need to be copied to all of the cores which would then create more cost than savings.
5) The dataframe approach is currently functional whereas it is unclear to me if the person-object approach would yield, right out of the box now, equally meaningful results without any modifications. 
6) Dataframes occupy a single memory block which allows for fast vectorized operations and fast ser/deser but also involves the copying of the data every time we append/concat the dataframes....
7) The current dataframe approach where a single number is stored on a single cell is not the only possibility. A list can be stored in a single cell thus reducing significantly the dataframe size. In addition, the ._sbp notation would be able to be used with person objects to get the sbp list as well as the dataframe notation to get the column-list. 
8) One could also imagine a 2D dataframe representation with the use of multi-indexing in order to create a 3D object (rows are people, columns are attributes, 3rd axis would be years). The cost of using multi-indexing with pandas is unclear to me.
9) One can also imagine using numpy array to represent the population, either 2D or 3D. That would involve setting each risk factor to its own column number since names are not utilized with numpy. For example sbpCol = 3 set as a constant and then popNPArray[0][sbpCol] would give all sbp values of person with index 0 (assuming a 3D numpy array) or popNPArray[0][sbpCol][0] would give the first sbp value of person 0. Numpy arrays would be faster to process than pandas dataframes due to the lack of indexing but they do have the same limitation/advantage of being stored in a continuous memory block.
10) Talking about a continuous memory block....the cost of concatenating dataframes/arrays could be minimized if at the beginning of the simulation a dataframe/array is created large enough to hold all the information (say all attributes, age, sbp, bmi etc) for all years. Then as the simulation progresses, concatenation would not take place but rather null values would be replaced by their actual numbers. That would mean no copying dataframes and increased memory usage that results from that. This would be fine if we knew exactly the memory we would need from the beginning but for somethings, like outcomes (stroke) the number of occurences for a person is unknown a priori....
11) One option for those parts of the simulation would be to utilize sparse numpy arrays using the same number of rows as the population array. So the popNPArray[0] would give you the array slice for person 0 (sbp, bmi etc) and popOutcomesSparseNPArray[0] would give you the slice of the sparse numpy array with all the outcomes for the same person (to avoid the need to join dataframes on the person index, which is an expensive operation). However, NP arrays were designed to hold numerical data (even though they can store objects I think). I have not used sparse pandas dataframes and I am not sure if they exist what their cost is.
12) But all of these would require a significant time investment.....that time investment would be worthwhile only if such investment would make the simulation future-proof.....the goal is not to optimize computing cost, but personnel cost + computing cost would be a better quantity to optimize, so the ability to modify code, develop new capabilities, discover logic mistakes, ability to minimize logic mistakes in the first place and the code performance are all important. 
13) Future-proof right now to me seems to be about the use of multiple cores and the use of simple/basic python structures, but I am less certain about the second one.... 
14) Regarding your second point above, I agree, since to make the simulation future-proof there is a need to design it for the use of multiple cores, adjusting the model itself once and for all rather than fixing things every time the "broken" model is used, would eliminate the need to communicate with the main core/process much, so that would increase the parallelizability of the code.

A choice needs to be made, do we have all the information we need though to make that choice?

**Comment by jburke5** [comment]
two thoughts:
1. we don’t need do do anything for performance. the current sim is slow, but we were able to run a massive number of trials on the existing infrastructure. running with the existing infrastructure is almost assuredly the most efficient in terms of your time!

2. our primary option, is whether we switch to person objects or keep a data frame based infrastructure.

is there a summary of the likely performance gains/losses of making that switch? i think that in terms of human input, it’s probably a long term win as it’ll give us a more readable codebase, which shoudl be easier to maintain and modify.

**Comment by deligkaris** [comment]
The results I have related to this....1) in my relatively simple test, the person objects were about 3 times faster than the dataframe (single core), 2) when I use the microsim code on risk factors, the person objects are only about 20% faster than the dataframe (single core). 

I wonder if this due to the fact that the dataframe approach has been optimized but less optimization has been done for the person object approach....or there are other costs associated with obtaining the risk factors that are so large where the relatively significant performance gains with person objects become less important.

With multiple cores things get more complicated, because the overhead of multiprocessing depends on the design (how many times we need to communicate back and forth).

**Comment by jburke5** [comment]
i thought you were planning a test of person objects vs. data frames on a realistic sized dataset at OSC while turning off calibration. did that happen?

**Comment by deligkaris** [comment]
No, that did not happen because I saw a difference in the implementation of the two (the risk factors were different, or something like that).

I tried a realistic sized dataset at OSC with exactly the same set of risk factors for the two approaches to make it as close as possible to a fair comparison...but I used multiprocessing for this test which makes interpretation difficult now...I will do the same on a single core and see what those results look like...

**Comment by jburke5** [comment]
i think that multiprocessing is the more fair test!

we want to compare what a reasonably optimized person object version of the system would look like compared to the existing data frame based implementation, on the hardware that we’ll run it on...

**Comment by deligkaris** [comment]
OK...let me add a few more tests on the OSC reasonably sized simulation and submit it....

**Comment by deligkaris** [comment]
Moved the simulation to entirely a person-based code.
