### ISSUE TITLE
random effects on GCP model

### ISSUE THREAD

**Issue by deligkaris** [jburke5/microsim#73]
A previous email exchange:

> A possible issue on gcp random effect:
>
> Population.py is using get_gcp_vectorized <[https://github.com/jburke5/microsim/blob/phenotype/microsim/population.py#L207](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Furldefense.com.mcas.ms%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fjburke5%2Fmicrosim%2Fblob%2Fphenotype%2Fmicrosim%2Fpopulation.py*L207__%3BIw!!AU3bcTlGKuA!D15IiUQq8yfdKaGz5j427YOuQy7HUKe55BZBGMp98ddjSmrBWfe7qap0u5YPnpprR8qMNWxGdVBQX2CIr-44lMebe9cF%24%3FMcasTsid%3D20893&McasCSRF=f628a247e20f8522d298a781d7c48843b6e8420cb0414454896f59fe6ed01132)> which includes a gcpRandomEffect <[https://github.com/jburke5/microsim/blob/phenotype/microsim/outcome_model_repository.py#L164](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Furldefense.com.mcas.ms%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fjburke5%2Fmicrosim%2Fblob%2Fphenotype%2Fmicrosim%2Foutcome_model_repository.py*L164__%3BIw!!AU3bcTlGKuA!D15IiUQq8yfdKaGz5j427YOuQy7HUKe55BZBGMp98ddjSmrBWfe7qap0u5YPnpprR8qMNWxGdVBQX2CIr-44lGXQ6cT6%24%3FMcasTsid%3D20893&McasCSRF=f628a247e20f8522d298a781d7c48843b6e8420cb0414454896f59fe6ed01132)> and then the get_risk_for_person of the gcp_model <[https://github.com/jburke5/microsim/blob/phenotype/microsim/outcome_model_repository.py#L164](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Furldefense.com.mcas.ms%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fjburke5%2Fmicrosim%2Fblob%2Fphenotype%2Fmicrosim%2Foutcome_model_repository.py*L164__%3BIw!!AU3bcTlGKuA!D15IiUQq8yfdKaGz5j427YOuQy7HUKe55BZBGMp98ddjSmrBWfe7qap0u5YPnpprR8qMNWxGdVBQX2CIr-44lGXQ6cT6%24%3FMcasTsid%3D20893&McasCSRF=f628a247e20f8522d298a781d7c48843b6e8420cb0414454896f59fe6ed01132)> includes another random effect and I am not sure if those two random effects represent something different or not.
>
> One is using person.gcpRandomEffect and the other one is using the dictionary person._randomEffects that includes the "gcp" key...but I think the first one is just a column from the dataframe (also see here) <[https://github.com/jburke5/microsim/blob/phenotype/microsim/person.py#L302](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Furldefense.com.mcas.ms%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fjburke5%2Fmicrosim%2Fblob%2Fphenotype%2Fmicrosim%2Fperson.py*L302__%3BIw!!AU3bcTlGKuA!D15IiUQq8yfdKaGz5j427YOuQy7HUKe55BZBGMp98ddjSmrBWfe7qap0u5YPnpprR8qMNWxGdVBQX2CIr-44lHL-aZGt%24%3FMcasTsid%3D20893&McasCSRF=f628a247e20f8522d298a781d7c48843b6e8420cb0414454896f59fe6ed01132)> whereas the second one is a person attribute.
>
> So it is possible the code is now adding the same thing two times but I am not entirely certain....
>

and JB's response:

you gave me a heart attack there for a minute, but i think we’re ok…

when you look at this method in the model: [https://github.com/jburke5/microsim/blob/d487de6f15072156e7cff223cae9957a734e9251/microsim/gcp_model.py#L107](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Furldefense.com.mcas.ms%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fjburke5%2Fmicrosim%2Fblob%2Fd487de6f15072156e7cff223cae9957a734e9251%2Fmicrosim%2Fgcp_model.py*L107__%3BIw!!AU3bcTlGKuA!D15IiUQq8yfdKaGz5j427YOuQy7HUKe55BZBGMp98ddjSmrBWfe7qap0u5YPnpprR8qMNWxGdVBQX2CIr-44lKdSf09I%24%3FMcasTsid%3D20893&McasCSRF=f628a247e20f8522d298a781d7c48843b6e8420cb0414454896f59fe6ed01132)

i thikn the get_risk_for_person() only ends up adding the gcp IF it is non-vectorized. the if statement on line 110 means that random_effect is zero if it is run in a vectorized setting…so, its only adding it at the end.

looking at this, though, it’d be cleaner to move the random effect to the person row wrapper and then access it all in the gcp model as opposed to having the random effect be implemented in the repository — that’s a lousy place to have substantive logic…

*******

I agree that things are OK as far as the vectorized version is concerned. I think that the non-vectorized approach however includes the gcp model's random effects two times, one from the [get_gcp method](https://github.com/deligkaris/microsim/blob/phenotype/microsim/outcome_model_repository.py#L154) and one
from the [get_risk_for_person method](https://github.com/deligkaris/microsim/blob/phenotype/microsim/gcp_model.py#L111). 

The solution I am proposing is to move all random effects, vectorized or not, for both gcp regular and gcp stroke models in the same place, the get_risk_for_person method.....

**Comment by jburke5** [comment]
got it. that sounds like the right way to do it...

**Comment by deligkaris** [comment]
The latest commit on the phenotype branch fixes this.
